config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount SimpleDiscussion::Engine => "/forum", constraints: -> { Flipper.enabled?(:forum) }

  require "sidekiq/web"

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Flipper::UI.app(Flipper) => "/flipper"
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/saml/sign_in', to: 'users/saml_sessions#new'
    post '/users/saml/auth', to: 'users/saml_sessions#create'
    get '/users/saml/metadata', to: 'users/saml_sessions#metadata'
  end

  # resources :assignment_submissions
  resources :group_members, only: %i[create destroy update]
  resources :groups, except: %i[index] do
    resources :assignments, except: %i[index]
    member do
      get "invite/:token", to: "groups#group_invite", as: "invite"
      put :generate_token
    end
  end

  resources :custom_mails, except: %i[destroy]
  get "/custom_mails/send_mail/:id", to: "custom_mails#send_mail", as: "send_custom_mail"
  get "/custom_mails/send_mail_to_self/:id", to: "custom_mails#send_mail_self",
                                             as: "send_custom_mail_self"

  # grades
  scope "/grades" do
    post "/", to: "grades#create", as: "grades"
    delete "/", to: "grades#destroy"
    get "/to_csv/:assignment_id", to: "grades#to_csv", as: "grades_to_csv"
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/search", to: "search#search"

  resources :about, only: :index
  resources :privacy, only: :index

  scope "/groups" do
    get "/:group_id/assignments/:id/reopen", to: "assignments#reopen", as: "reopen_group_assignment"
    put "/:group_id/assignments/:id/close", to: "assignments#close", as: "close_group_assignment"
    get "/:group_id/assignments/:id/start", to: "assignments#start", as: "assignment_start"
  end
  resources :stars, only: %i[create destroy]

  resources :featured_circuits, only: %i[index create]
  delete "/featured_circuits", to: "featured_circuits#destroy"

  get "/users/edit", to: redirect('/')
  devise_for :users, controllers: {
    registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions", :saml_sessions => "users/saml_sessions"
  }

  # Circuitverse web pages resources
  root "circuitverse#index"
  get  "/examples", to: "circuitverse#examples"
  get  "/tos", to: "circuitverse#tos"
  get  "/teachers", to: "circuitverse#teachers"
  get  "/contribute", to: "circuitverse#contribute"

  #announcements
  resources :announcements, except: %i[show]

  # users

  scope "/users" do
    get "/:id/profile", to: redirect('/users/%{id}'), as: "profile"
    get "/:id/profile/edit", to: "users/circuitverse#edit", as: "profile_edit"
    patch "/:id/update", to: "users/circuitverse#update", as: "profile_update"
    get "/:id/groups", to: "users/circuitverse#groups", as: "user_groups"
    get "/:id/", to: "users/circuitverse#index", as: "user_projects"
    get "/educational_institute/typeahead/:query" => "users/circuitverse#typeahead_educational_institute"
    get "/:id/notifications", to: "users/noticed_notifications#index", as: "notifications"
    patch "/:id/notifications/mark_all_as_read", to: "users/noticed_notifications#mark_all_as_read", as: "mark_all_as_read"
    patch "/:id/notifications/read_all_notifications", to: "users/noticed_notifications#read_all_notifications", as: "read_all_notifications"
    post "/:id/notifications/mark_as_read/:notification_id", to: "users/noticed_notifications#mark_as_read", as: "mark_as_read"
  end

  post "/push/subscription/new", to: "push_subscription#create"
  post "/push/test", to: "push_subscription#test"

  # projects
  scope "/projects" do
    post "/create_fork/:id", to: "projects#create_fork", as: "create_fork_project"
    get "/change_stars/:id", to: "projects#change_stars", as: "change_stars"
    get "tags/:tag", to: "projects#get_projects", as: "tag"
  end

  # lti
  scope "lti"  do
    match 'launch', to: 'lti#launch', via: [:get, :post]
  end

  mount Commontator::Engine => "/commontator"

  # Default route for Vue simulator
  get 'simulatorvue', to: 'static#simulatorvue', as: 'default_simulatorvue'

  # Vue simulaltor Route with catchall
  get 'simulatorvue/*path', to: 'static#simulatorvue', as: 'simulatorvue'

  # simulator
  scope "/simulator" do
    get "/:id", to: "simulator#show", as: "simulator"
    get "/edit/:id", to: "simulator#edit", as: "simulator_edit"
    post "/get_data", to: "simulator#get_data"
    get "get_data/:id", to: "simulator#get_data"
    post "/post_issue", to: "simulator#post_issue"
    get "/issue_circuit_data/:id", to: "simulator#view_issue_circuit_data"
    post "/update_data", to: "simulator#update"
    post "/update_image", to: "simulator#update_image"
    post "/create_data", to: "simulator#create"
    post "/verilogcv", to: "simulator#verilog_cv"
    get "/", to: "simulator#new", as: "simulator_new"
    get "/embed/:id", to: "simulator#embed", as: "simulator_embed"
  end

  scope "/testbench" do
    get "/", to: "testbench#creator", as: "testbench_creator"
  end
  # get 'simulator/embed_cross/:id', to: 'simulator#embed_cross', as: 'simulator_embed_cross'

  resources :users do
    resources :projects, except: %i[index new]
  end
  resources :collaborations, only: %i[create destroy update]

  # redirects
  get "/facebook", to: redirect("https://www.facebook.com/CircuitVerse")
  get "/twitter", to: redirect("https://www.twitter.com/CircuitVerse")
  get "/linkedin", to: redirect("https://www.linkedin.com/company/circuitverse")
  get "/youtube", to: redirect("https://www.youtube.com/@circuitverse4457")
  get "/slack", to: redirect(
    "https://join.slack.com/t/circuitverse-team/shared_invite/zt-2yo74pd8x-3uhWIZzNpzJwHcbU7oLL3A"
  )
  get "/discord", to: redirect("https://discord.gg/8G6TpmM")
  get "/github", to: redirect("https://github.com/CircuitVerse")
  get "/learn", to: redirect("https://learn.circuitverse.org")
  get "/docs", to: redirect("https://docs.circuitverse.org")
  get "/features", to: redirect("/#home-features-section")

  # Health Check at /up ~> will be default in rails 7.1
  get '/up', to: ->(_env) { [200, {}, ['']] }

  # get 'comments/create_reply/:id', to: 'comments#create_reply', as: 'reply_comment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      post "/auth/login", to: "authentication#login"
      post "/auth/signup", to: "authentication#signup"
      post "/oauth/login", to: "authentication#oauth_login"
      post "/oauth/signup", to: "authentication#oauth_signup"
      get  "/public_key.pem", to: "authentication#public_key"
      post "/password/forgot", to: "authentication#forgot_password"
      get "/notifications", to: "notifications#index"
      patch "/notifications/mark_as_read/:notification_id", to: "notifications#mark_as_read"
      patch "/notifications/mark_all_as_read", to: "notifications#mark_all_as_read"
      get "/me", to: "users#me"
      post "/forgot_password", to: "users#forgot_password"
      resources :users, only: %i[index show update]
      get "/projects/featured", to: "projects#featured_circuits"
      get "/projects/search", to: "projects#search"
      post "/simulator/post_issue", to: "simulator#post_issue"
      post "/simulator/verilogcv", to: "simulator#verilog_cv"
      resources :projects, only: %i[index show create update destroy] do
        collection do
          patch :update_circuit, path: "update_circuit"
        end
        member do
          get "toggle-star", to: "projects#toggle_star"
          post "fork", to: "projects#create_fork"
          get "image_preview", to: "projects#image_preview"
          get :circuit_data
          get :check_edit_access
        end
        resources :collaborators, only: %i[index create destroy]
      end
      resources :users do
        member do
          get "projects", to: "projects#user_projects"
          get "favourites", to: "projects#user_favourites"
          # get "projects/all", to: "projects#all_user_projects"
        end
      end
      post "/assignments/:assignment_id/projects/:project_id/grades", to: "grades#create"
      resources :grades, only: %i[update destroy]
      get "/groups/owned", to: "groups#groups_owned"
      resources :groups, only: %i[index show update destroy]
      delete "/group/members/:id", to: "group_members#destroy"
      put "/group/members/:id", to: "group_members#update"
      patch "/group/members/:id", to: "group_members#update"
      resources :groups do
        resources :members, controller: "group_members", shallow: true, only: %i[index create]
        resources :assignments, shallow: true
      end
      resources :assignments do
        member do
          patch "reopen"
          patch "start"
        end
      end
      resources :threads, only: %i[close reopen] do
        resources :comments, only: %i[index create update], shallow: true do
          member do
            put "upvote"
            put "downvote"
            put "unvote"

            put "delete"
            put "undelete"
          end
        end

        member do
          put "close"
          put "reopen"

          put "subscribe"
          put "unsubscribe"
        end
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_secure_token :group_token
  validates :name, length: { minimum: 1 }, presence: true
  belongs_to :primary_mentor, class_name: "User"
  has_many :group_members, dependent: :destroy
  has_many :users, through: :group_members

  has_many :assignments, dependent: :destroy
  has_many :pending_invitations, dependent: :destroy

  after_commit :send_creation_mail, on: :create
  scope :with_valid_token, -> { where("token_expires_at >= ?", Time.zone.now) }
  TOKEN_DURATION = 12.days

  def send_creation_mail
    GroupMailer.new_group_email(primary_mentor, self).deliver_later
  end

  def has_valid_token?
    token_expires_at.present? && token_expires_at > Time.zone.now
  end

  def reset_group_token
    transaction do
      regenerate_group_token
      update(token_expires_at: Time.zone.now + TOKEN_DURATION)
    end
  end
end

app/controllers/api/v1/groups_controller.rb
# frozen_string_literal: true

class Api::V1::GroupsController < Api::V1::BaseController
  before_action :authenticate_user!
  before_action :set_group, except: %i[index groups_owned create]
  before_action :set_options, only: %i[index groups_owned create show update]
  before_action :check_show_access, only: [:show]
  before_action :check_edit_access, only: %i[update destroy]

  WHITELISTED_INCLUDE_ATTRIBUTES = %i[group_members assignments].freeze

  # GET /api/v1/groups
  def index
    @groups = paginate(current_user.groups)
    @options[:links] = link_attrs(@groups, api_v1_groups_url)
    render json: Api::V1::GroupSerializer.new(@groups, @options)
  end

  # GET /api/v1/groups/owned
  def groups_owned
    @groups = paginate(current_user.groups_owned)
    @options[:links] = link_attrs(@groups, api_v1_groups_owned_url)
    render json: Api::V1::GroupSerializer.new(@groups, @options)
  end

  # GET /api/v1/groups/:id
  def show
    render json: Api::V1::GroupSerializer.new(@group, @options)
  end

  # POST /api/v1/groups/
  def create
    @group = current_user.groups_owned.new(group_params)
    @group.save!
    if @group.save
      render json: Api::V1::GroupSerializer.new(@group, @options), status: :created
    else
      invalid_resource!(@group.errors)
    end
  end

  # PATCH /api/v1/groups/:id
  def update
    @group.update!(group_params)
    if @group.update(group_params)
      render json: Api::V1::GroupSerializer.new(@group), status: :accepted
    else
      invalid_resource!(@group.errors)
    end
  end

  # DELETE /api/v1/groups/:id
  def destroy
    @group.destroy!
    head :no_content
  end

  private

    # include=group_members,assignments
    def include_resource
      params[:include].split(",")
                      .map { |resource| resource.strip.to_sym }
                      .select { |resource| WHITELISTED_INCLUDE_ATTRIBUTES.include?(resource) }
    end

    def set_group
      @group = Group.find(params[:id])
    end

    def set_options
      @options = {}
      @options[:include] = include_resource if params.key?(:include)
      @options[:params] = { current_user: current_user }
    end

    def group_params
      params.require(:group).permit(:name, :primary_mentor_id)
    end

    def check_show_access
      authorize @group, :show_access?
    end

    def check_edit_access
      authorize @group, :admin_access?
    end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy group_invite generate_token]
  before_action :authenticate_user!
  before_action :check_show_access, only: %i[show edit update destroy]
  before_action :check_edit_access, only: %i[edit update destroy generate_token]

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group_member = @group.group_members.new
    @group.assignments.each do |assignment|
      if (assignment.status == "reopening") && (assignment.deadline < Time.zone.now)
        assignment.status = "closed"
        assignment.save
      end
    end
  end

  def generate_token
    @group = Group.find(params[:id])
    @group.reset_group_token unless @group.has_valid_token?
  end

  def group_invite
    if Group.with_valid_token.exists?(group_token: params[:token])
      if current_user.groups.exists?(id: @group)
        notice = "Member is already present in the group."
      else
        current_user.group_members.create!(group: @group)
        notice = "Group member was successfully added."
      end
    elsif Group.exists?(group_token: params[:token])
      notice = "Url is expired, request a new one from the primary mentor of the group."
    else
      notice = "Invalid url"
    end
    redirect_to group_path(@group), notice: notice
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups_owned.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html do
        redirect_to user_groups_path(current_user), notice: "Group was successfully deleted."
      end
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :primary_mentor_id)
    end

    def check_show_access
      authorize @group, :show_access?
    end

    def check_edit_access
      authorize @group, :admin_access?
    end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/_add_member_modal.html.erb
<div id="addmemberModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header primary-modal-header">
        <h4 class="modal-title"><%= t("add_members") %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
      </div>
      <div class="modal-body">
        <p><%= t("groups.add_member_description") %></p>
        <%= form_with(model: group_member, local: true) do |form| %>
          <% if group_member.errors.any? %>
            <div class="error-message">
              <ul>
                <% group_member.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.hidden_field :group_id, id: :group_member_group_id %>
          </div>
          <div class="field">
            <%= form.hidden_field :mentor, value: false %>
          </div>
          <div class="mb-3 d-flex flex-column">
            <%= form.label :emails %>
            <%= form.select :emails, [], {}, { class: "form-select", multiple: true } %>
          </div>
          <div class="modal-footer">
            <%= form.submit class: "btn primary-button", id: "add-members-button" %>
          </div>
        <% end %>
      </div>
      <div class="mx-auto text-center p-3">
        <p><%= t("groups.use_alternative") %></p>
        <%= button_to generate_token_group_path, { remote: true, method: :put, class: "btn primary-button", "data-bs-toggle": "collapse", href: "#group-invite-link-container", "aria-expanded": "false", "aria-controls": "group-invite-link-container" } do %>
          <i class="fas fa-external-link-alt"></i>
          <span><%= t("groups.invite_link_btn") %></span>
        <% end %>
        <div class="collapse" id="group-invite-link-container">
          <textarea readonly="readonly" id="embedInviteLink" class="group-invite-link-text" rows="3" cols="35" name="group-invite-link"></textarea>
          <i class="fas fa-2x fa-regular fa-copy" onclick="copyToClipboard()" id="copyIcon" style="cursor:pointer"></i>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
function copyToClipboard(){
  var copyText=document.getElementById("embedInviteLink");
  var copyIcon=document.getElementById("copyIcon");
  copyIcon.classList.add("text-success");
  copyText.select();
  document.execCommand('copy');
  alert("Invite link copied to clipboard");
}
</script>

app/views/groups/_add_mentor_modal.html.erb
<div id="add-mentor-to-modal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header primary-modal-header">
        <h4 class="modal-title"><%= t("add_mentors") %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
      </div>
      <div class="modal-body">
        <p><%= t("groups.add_member_description") %></p>
        <%= t("groups.add_mentor_description_html") %>
        <%= form_with(model: group_member, local: true) do |form| %>
          <% if group_member.errors.any? %>
            <div class="error-message">
              <ul>
                <% group_member.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.hidden_field :group_id, id: :group_member_group_id %>
          </div>
          <div class="field">
            <%= form.hidden_field :mentor, value: true %>
          </div>
          <div class="mb-3 d-flex flex-column">
            <%= form.label :emails %>
            <%= form.select :emails, [], {}, { class: "form-select", id: "group_mentor_emails", multiple: true } %>
          </div>
          <div class="modal-footer">
            <%= form.submit "Add mentors", class: "btn primary-button", id: "add-mentor-button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_delete_assignment_confirmation_modal.html.erb
<div id="deleteassignmentModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header secondary-modal-header">
        <h4 class="modal-title"><%= t("delete") %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
      </div>
      <div class="modal-body">
        <p><%= t("groups.remove_assignment_message") %></p>
      </div>
      <div class="modal-footer">
        <%= link_to "#", method: :delete, class: "btn primary-delete-button", id: "groups-assignment-delete-button" do %>
          <%= t("delete") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_delete_member_confirmation_modal.html.erb
<div id="deletememberModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header secondary-modal-header">
        <h4 class="modal-title"><%= t("delete") %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
      </div>
      <div class="modal-body">
        <p><%= t("groups.remove_member_message") %></p>
      </div>
      <div class="modal-footer">
        <%= link_to "#", method: :delete, class: "btn primary-delete-button", id: "groups-member-delete-button" do %>
          <%= t("delete") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div class="error-message">
      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-3 groups-form-text-container">
    <div class="field mb-3">
      <h5><%= form.label :name %></h5>
      <div class="input-group groups-input-group">
        <%= form.text_field :name, id: :group_name, class: "form-control form-input", autofocus: true %>
      </div>
    </div>
  </div>
  <div class="groups-form-text-container">
    <%= form.submit class: "btn primary-button groups-form-primary-button" %>
    <%= link_to t("back"), :back, class: "groups-form-anchor-text anchor-text" %>
  </div>
<% end %>

app/views/groups/_group_members.html.erb
<% group.group_members.member.each do |member| %>
  <div class="<%= membersCardViewerContainer(group) %>">
    <div class="<%= membersCardViewer(group) %>">
      <div class="row">
        <div class="<%= membersCardViewerDetail(group) %>">
          <span class="groups-members-card-avatar">
          <% if member.user.profile_picture.present? %>
          <%= link_to image_tag(member.user.profile_picture.url, alt: member.user.name, title: "#{member.user.name}\n#{member.user.email}"), user_path(member.user.id) %>          <% else %>
          <i class="fa fa-user default-profile-icon"></i>
          <% end %>
          </span>
          <div class="groups-members-card-name-container">
            <span class="tooltiptext"><%= member.user.name %></span>
            <%= link_to member.user.name, member.user, class: "groups-members-card-name", title: "view profile of #{member.user.name}" %>
          </div>
          <% if policy(group).admin_access? %>
            <p class="groups-members-card-email" title="<%= member.user.email %>"><%= member.user.email %></p>
          <% end %>
        </div>
        <% if policy(group).admin_access? %>
          <div class="group-member-button-container">
            <div class="groups-mentor-card-mini-buttons">
              <%= link_to "#", data: { bs_toggle: "modal", bs_target: "#deletememberModal", currentgroupmember: GroupMember.find_by(user_id: member.user.id, group_id: group.id).id }, class: "mini-button groups-delete-mini-button" do %>
                <%= image_tag("SVGs/deleteGroup.svg", alt: "Remove Member") %>
                <span><%= t("remove") %></span>
              <% end %>
              <%= link_to "#", data: { bs_toggle: "modal", bs_target: "#promote-member-modal", currentgroupmember: GroupMember.find_by(user_id: member.user.id, group_id: group.id).id }, class: "mini-button groups-reopen-mini-button" do %>
                <%= image_tag("SVGs/editGroup.svg", alt: "Make Member") %>
                <span><%= t("groups.make_mentor") %></span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/_group_mentors.html.erb
<% group.group_members.mentor.each do |member| %>
  <div class="<%= membersCardViewerContainer(group) %>">
    <div class="<%= membersCardViewer(group) %>">
      <div class="row">
        <div class="<%= membersCardViewerDetail(group) %>">
        <span class="groups-members-card-avatar">
        <% if member.user.profile_picture.present? %>
        <%= link_to image_tag(member.user.profile_picture.url, alt: member.user.name, title: "#{member.user.name}\n#{member.user.email}"), user_path(member.user.id) %>        <% else %>
        <i class="fa fa-user"></i>
        <% end %>
        </span>
          <div class="groups-members-card-name-container">
            <span class="tooltiptext"><%= member.user.name %></span>
            <%= link_to member.user.name, member.user, class: "groups-members-card-name", title: "view profile of #{member.user.name}" %>
          </div>
          <% if policy(group).admin_access? %>
            <p class="groups-members-card-email" title="<%= member.user.email %>"><%= member.user.email %></p>
          <% end %>
        </div>
        <% if policy(group).admin_access? %>
          <div class="group-member-button-container">
            <div class="groups-mentor-card-mini-buttons">
              <%= link_to "#", data: { bs_toggle: "modal", bs_target: "#deletememberModal", currentgroupmember: GroupMember.find_by(user_id: member.user.id, group_id: group.id).id }, class: "mini-button groups-delete-mini-button" do %>
                <%= image_tag("SVGs/deleteGroup.svg", alt: "Remove Member") %>
                <span><%= t("remove") %></span>
              <% end %>
              <%= link_to "#", data: { bs_toggle: "modal", bs_target: "#demote-member-modal", currentgroupmember: GroupMember.find_by(user_id: member.user.id, group_id: group.id).id }, class: "mini-button groups-reopen-mini-button" do %>
                <%= image_tag("SVGs/editGroup.svg", alt: "Make mentor") %>
                <span><%= t("groups.make_member") %></span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/_promote_member_confirmation_modal.html.erb
<div id="promote-member-modal" class="modal fade" role="dialog" data-controller="groups">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header primary-modal-header">
        <h4 class="modal-title"><%= t("groups.make_mentor") %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
      </div>
      <div class="modal-body">
        <%= t("groups.promote_member_confirmation") %>
        <%= t("groups.add_mentor_description_html") %>
      </div>
      <div class="modal-footer">
        <%= button_to "#", params: { group_member: { mentor: true } }, method: :patch, class: "btn primary-button", id: "groups-member-promote-button" do %>
          <%= t("groups.make_mentor") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="demote-member-modal" class="modal fade" role="dialog" data-controller="groups">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header primary-modal-header">
        <h4 class="modal-title"><%= t("groups.make_member") %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
      </div>
      <div class="modal-body">
        <%= t("groups.demote_mentor_confirmation") %>
        <%= t("groups.add_mentor_description_html") %>
      </div>
      <div class="modal-footer">
        <%= button_to "#", params: { group_member: { mentor: false } }, method: :patch, class: "btn primary-button", id: "groups-member-demote-button" do %>
          <%= t("groups.make_member") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/generate_token.js.erb
$("#embedInviteLink").html("<%= group_url(@group) %>/invite/<%= @group.group_token %> ");