config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount SimpleDiscussion::Engine => "/forum", constraints: -> { Flipper.enabled?(:forum) }

  require "sidekiq/web"

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Flipper::UI.app(Flipper) => "/flipper"
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/saml/sign_in', to: 'users/saml_sessions#new'
    post '/users/saml/auth', to: 'users/saml_sessions#create'
    get '/users/saml/metadata', to: 'users/saml_sessions#metadata'
  end

  # resources :assignment_submissions
  resources :group_members, only: %i[create destroy update]
  resources :groups, except: %i[index] do
    resources :assignments, except: %i[index]
    member do
      get "invite/:token", to: "groups#group_invite", as: "invite"
      put :generate_token
    end
  end

  resources :custom_mails, except: %i[destroy]
  get "/custom_mails/send_mail/:id", to: "custom_mails#send_mail", as: "send_custom_mail"
  get "/custom_mails/send_mail_to_self/:id", to: "custom_mails#send_mail_self",
                                             as: "send_custom_mail_self"

  # grades
  scope "/grades" do
    post "/", to: "grades#create", as: "grades"
    delete "/", to: "grades#destroy"
    get "/to_csv/:assignment_id", to: "grades#to_csv", as: "grades_to_csv"
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/search", to: "search#search"

  resources :about, only: :index
  resources :privacy, only: :index

  scope "/groups" do
    get "/:group_id/assignments/:id/reopen", to: "assignments#reopen", as: "reopen_group_assignment"
    put "/:group_id/assignments/:id/close", to: "assignments#close", as: "close_group_assignment"
    get "/:group_id/assignments/:id/start", to: "assignments#start", as: "assignment_start"
  end
  resources :stars, only: %i[create destroy]

  resources :featured_circuits, only: %i[index create]
  delete "/featured_circuits", to: "featured_circuits#destroy"

  get "/users/edit", to: redirect('/')
  devise_for :users, controllers: {
    registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions", :saml_sessions => "users/saml_sessions"
  }

  # Circuitverse web pages resources
  root "circuitverse#index"
  get  "/examples", to: "circuitverse#examples"
  get  "/tos", to: "circuitverse#tos"
  get  "/teachers", to: "circuitverse#teachers"
  get  "/contribute", to: "circuitverse#contribute"

  #announcements
  resources :announcements, except: %i[show]

  # users

  scope "/users" do
    get "/:id/profile", to: redirect('/users/%{id}'), as: "profile"
    get "/:id/profile/edit", to: "users/circuitverse#edit", as: "profile_edit"
    patch "/:id/update", to: "users/circuitverse#update", as: "profile_update"
    get "/:id/groups", to: "users/circuitverse#groups", as: "user_groups"
    get "/:id/", to: "users/circuitverse#index", as: "user_projects"
    get "/educational_institute/typeahead/:query" => "users/circuitverse#typeahead_educational_institute"
    get "/:id/notifications", to: "users/noticed_notifications#index", as: "notifications"
    patch "/:id/notifications/mark_all_as_read", to: "users/noticed_notifications#mark_all_as_read", as: "mark_all_as_read"
    patch "/:id/notifications/read_all_notifications", to: "users/noticed_notifications#read_all_notifications", as: "read_all_notifications"
    post "/:id/notifications/mark_as_read/:notification_id", to: "users/noticed_notifications#mark_as_read", as: "mark_as_read"
  end

  post "/push/subscription/new", to: "push_subscription#create"
  post "/push/test", to: "push_subscription#test"

  # projects
  scope "/projects" do
    post "/create_fork/:id", to: "projects#create_fork", as: "create_fork_project"
    get "/change_stars/:id", to: "projects#change_stars", as: "change_stars"
    get "tags/:tag", to: "projects#get_projects", as: "tag"
  end

  # lti
  scope "lti"  do
    match 'launch', to: 'lti#launch', via: [:get, :post]
  end

  mount Commontator::Engine => "/commontator"

  # Default route for Vue simulator
  get 'simulatorvue', to: 'static#simulatorvue', as: 'default_simulatorvue'

  # Vue simulaltor Route with catchall
  get 'simulatorvue/*path', to: 'static#simulatorvue', as: 'simulatorvue'

  # simulator
  scope "/simulator" do
    get "/:id", to: "simulator#show", as: "simulator"
    get "/edit/:id", to: "simulator#edit", as: "simulator_edit"
    post "/get_data", to: "simulator#get_data"
    get "get_data/:id", to: "simulator#get_data"
    post "/post_issue", to: "simulator#post_issue"
    get "/issue_circuit_data/:id", to: "simulator#view_issue_circuit_data"
    post "/update_data", to: "simulator#update"
    post "/update_image", to: "simulator#update_image"
    post "/create_data", to: "simulator#create"
    post "/verilogcv", to: "simulator#verilog_cv"
    get "/", to: "simulator#new", as: "simulator_new"
    get "/embed/:id", to: "simulator#embed", as: "simulator_embed"
  end

  scope "/testbench" do
    get "/", to: "testbench#creator", as: "testbench_creator"
  end
  # get 'simulator/embed_cross/:id', to: 'simulator#embed_cross', as: 'simulator_embed_cross'

  resources :users do
    resources :projects, except: %i[index new]
  end
  resources :collaborations, only: %i[create destroy update]

  # redirects
  get "/facebook", to: redirect("https://www.facebook.com/CircuitVerse")
  get "/twitter", to: redirect("https://www.twitter.com/CircuitVerse")
  get "/linkedin", to: redirect("https://www.linkedin.com/company/circuitverse")
  get "/youtube", to: redirect("https://www.youtube.com/@circuitverse4457")
  get "/slack", to: redirect(
    "https://join.slack.com/t/circuitverse-team/shared_invite/zt-2yo74pd8x-3uhWIZzNpzJwHcbU7oLL3A"
  )
  get "/discord", to: redirect("https://discord.gg/8G6TpmM")
  get "/github", to: redirect("https://github.com/CircuitVerse")
  get "/learn", to: redirect("https://learn.circuitverse.org")
  get "/docs", to: redirect("https://docs.circuitverse.org")
  get "/features", to: redirect("/#home-features-section")

  # Health Check at /up ~> will be default in rails 7.1
  get '/up', to: ->(_env) { [200, {}, ['']] }

  # get 'comments/create_reply/:id', to: 'comments#create_reply', as: 'reply_comment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      post "/auth/login", to: "authentication#login"
      post "/auth/signup", to: "authentication#signup"
      post "/oauth/login", to: "authentication#oauth_login"
      post "/oauth/signup", to: "authentication#oauth_signup"
      get  "/public_key.pem", to: "authentication#public_key"
      post "/password/forgot", to: "authentication#forgot_password"
      get "/notifications", to: "notifications#index"
      patch "/notifications/mark_as_read/:notification_id", to: "notifications#mark_as_read"
      patch "/notifications/mark_all_as_read", to: "notifications#mark_all_as_read"
      get "/me", to: "users#me"
      post "/forgot_password", to: "users#forgot_password"
      resources :users, only: %i[index show update]
      get "/projects/featured", to: "projects#featured_circuits"
      get "/projects/search", to: "projects#search"
      post "/simulator/post_issue", to: "simulator#post_issue"
      post "/simulator/verilogcv", to: "simulator#verilog_cv"
      resources :projects, only: %i[index show create update destroy] do
        collection do
          patch :update_circuit, path: "update_circuit"
        end
        member do
          get "toggle-star", to: "projects#toggle_star"
          post "fork", to: "projects#create_fork"
          get "image_preview", to: "projects#image_preview"
          get :circuit_data
          get :check_edit_access
        end
        resources :collaborators, only: %i[index create destroy]
      end
      resources :users do
        member do
          get "projects", to: "projects#user_projects"
          get "favourites", to: "projects#user_favourites"
          # get "projects/all", to: "projects#all_user_projects"
        end
      end
      post "/assignments/:assignment_id/projects/:project_id/grades", to: "grades#create"
      resources :grades, only: %i[update destroy]
      get "/groups/owned", to: "groups#groups_owned"
      resources :groups, only: %i[index show update destroy]
      delete "/group/members/:id", to: "group_members#destroy"
      put "/group/members/:id", to: "group_members#update"
      patch "/group/members/:id", to: "group_members#update"
      resources :groups do
        resources :members, controller: "group_members", shallow: true, only: %i[index create]
        resources :assignments, shallow: true
      end
      resources :assignments do
        member do
          patch "reopen"
          patch "start"
        end
      end
      resources :threads, only: %i[close reopen] do
        resources :comments, only: %i[index create update], shallow: true do
          member do
            put "upvote"
            put "downvote"
            put "unvote"

            put "delete"
            put "undelete"
          end
        end

        member do
          put "close"
          put "reopen"

          put "subscribe"
          put "unsubscribe"
        end
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  include ActionView::Helpers::SanitizeHelper
  include SanitizeDescription
  include UsersCircuitverseHelper

  before_action :set_project, only: %i[show edit update destroy create_fork change_stars]
  before_action :authenticate_user!, only: %i[edit update destroy create_fork change_stars]

  before_action :check_access, only: %i[edit update destroy]
  before_action :check_delete_access, only: [:destroy]
  before_action :check_view_access, only: %i[show create_fork]
  before_action :sanitize_name, only: %i[create update]
  before_action :sanitize_project_description, only: %i[show edit]

  # GET /projects
  # GET /projects.json
  def index
    @author = User.find(params[:user_id])
  end

  # GET /projects/tags/[tag]
  def get_projects
    @projects = Project.tagged_with(params[:tag]).open.includes(:tags, :author)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if current_visit && !Ahoy::Event.exists?(visit_id: current_visit.id,
                                             name: "Visited project #{@project.id}")
      ahoy.track("Visited project #{@project.id}")
      @project.increase_views(current_user)
    end
    @collaboration = @project.collaborations.new
    @admin_access = true
    commontator_thread_show(@project)
  end

  # GET /projects/1/edit
  def edit; end

  def change_stars
    star = Star.find_by(user_id: current_user.id, project_id: @project.id)
    if star.nil?
      @star = Star.new
      @star.user_id = current_user.id
      @star.project_id = @project.id
      @star.save
      render js: "2"
    else
      star.destroy
      render js: "1"
    end
  end

  def create_fork
    authorize @project
    @project_new = @project.fork(current_user)
    @project_new.save!
    redirect_to user_project_path(current_user, @project_new)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.create(project_params)

    respond_to do |format|
      if @project.save
        format.html do
          redirect_to user_project_path(@project.author_id, @project),
                      notice: "Project was successfully created."
        end
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @project.description = params["description"]
    respond_to do |format|
      if @project.update(project_params)
        format.html do
          redirect_to user_project_path(@project.author_id, @project),
                      notice: "Project was successfully updated."
        end
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html do
        redirect_to user_path(@project.author_id), notice: "Project was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      if params[:user_id]
        @author = User.find(params[:user_id])
        @project = @author.projects.friendly.find(params[:id])
      else
        @project = Project.friendly.find(params[:id])
        @author = @project.author
      end
    end

    def check_access
      authorize @project, :edit_access?
    end

    def check_delete_access
      authorize @project, :author_access?
    end

    def check_view_access
      authorize @project, :view_access?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :project_access_type, :description, :tag_list, :tags)
    end

    def sanitize_name
      params[:project][:name] = sanitize(project_params[:name])
    end

    # Sanitize description before passing to view
    def sanitize_project_description
      @project.description = sanitize_description(@project.description)
    end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_delete_collaboration_confirmation_modal.html.erb
<div id="deletecollaborationModal" class="modal fade" role="dialog">
  <div class="modal-dialog primary-modal-dialog">
    <div class="modal-content">
      <div class="modal-header secondary-modal-header">
        <h4 class="modal-title"><%= t("delete") %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
      </div>
      <div class="modal-body">
        <p><%= t("projects.remove_collaborator_message") %></p>
      </div>
      <div class="modal-footer">
        <%= link_to "#", method: :delete, class: "btn primary-delete-button", id: "projects-collaboration-delete-button" do %>
        <%= t("delete") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<% content_for :title, t("projects.edit.title", name: @project.name) %>

<div class="container projects-new-container">
  <div class="row center-row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
      <h1 class="submain-heading"><%= t("projects.edit.main_heading") %></h1> <br>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
      <div class="form-container">
        <%= render "form", project: @project %>
      </div>
    </div>
  </div>
</div>

app/views/projects/get_projects.html.erb
<div class="container">
  <div class="row center-row">
    <div class="col-12">
      <br>
      <h1 class="search-tag-heading"><%= t("projects.get_projects.searched_projects_heading") %></h1>
      <h2 class="search-tag-heading"><%= t("projects.get_projects.searched_tags_heading") %> <span class="badge search-tag"><%= params[:tag] %></span> </h2>
    </div>
  </div>
</div>

<div class="container search-tag-search-container">
  <% @projects.each do |project| %>
    <div class="row center-row">
      <div class="col-12 col-sm-12 col-md-5 col-lg-5">
        <div class="row center-row">
          <%= image_tag project_image_preview(project, current_user), alt: "project.name", class: "search-image" %>
        </div>
        <div class="row center-row search-view-count-container">
          <i class="fas fa-star search-star-count-icon" aria-hidden="true"></i>
          <span id="star-count" class="noSelect"><%= project.stars.count %></span>
           <%= t("projects.stars_count") %>
          &nbsp; &nbsp;
          <i class="fa fa-eye" aria-hidden="true"></i>
          <span id="star-count" class="noSelect"><%= project.view %></span>
           <%= t("projects.views_count") %>
        </div>
        <div class="row center-row search-user-data-container">
          <h6 class="search-user-heading"><%= t("projects.project_user") %></h6>
          <div class="search-user-data">
            <%= image_tag user_profile_picture(project.author.profile_picture), alt: "User Image", class: "search-user-image" %>
            <%= link_to project.author.name, project.author, class: "search-user-link anchor-text" %>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-7 col-lg-7">
        <div class="row center-row">
          <div class="col-8 col-sm-8 col-md-8 col-lg-8 search-project-detail-container">
            <div class="row center-row">
              <h3 class="search-project-name"><%= project.name %></h3>
              <span class="tooltiptext"><%= project.name %></span>
            </div>
            <div class="row center-row">
              <div class="search-tag-container">
                <% if !project.tags.empty? %>
                  <% project.tags.each do |tag| %>
                    <%= link_to tag.name, tag_path(tag.name), class: "badge search-tag" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-4 col-sm-4 col-md-4 col-lg-4 search-project-detail-container">
            <a class="btn primary-button search-primary-button" target="_blank" href="<%= user_project_path(project.author, project) %>" role="button"><%= t("view") %></a>
          </div>
        </div>
        <div class="row center-row">
          <div class="search-project-description"><%= sanitize project.description %></div>
        </div>
      </div>
    </div>
    <hr class="search-horizontal-rule">
  <% end %>
</div>

app/views/projects/show.html.erb
<% content_for :title, "CircuitVerse - #{@project.name}" %>
<% content_for :description, @project.description %>
<% set_meta_tags author: @project.author.name %>
<% set_meta_tags twitter: {
     card: "summary_large_image",
     title: yield(:title),
     description: @project.description,
     image: {
       src: "#{Rails.configuration.site_url}#{@project.image_preview}"
     }
   } %>
<% set_meta_tags og: {
     title: yield(:title),
     image: "#{Rails.configuration.site_url}#{@project.image_preview}",
     description: @project.description,
     type: "article",
     site_name: Rails.configuration.site_name
   } %>
<div class="container" data-controller="projects">
  <% if notice %>
  <div class="row" id='alertdiv'>
    <div class="alert alert-success alert-dismissible container text-center">
      <a href="#" class="btn-close" data-bs-dismiss="alert" aria-label="close"></a>
      <h6><%= notice %></h6>
    </div>
  </div>
  <% end %>
  <br>
  <div class="row center-row">
    <div class="col-12 col-sm-12 col-md-7 col-lg-7 ">
      <div class="projects-iframe-container">
        <div class="ratio ratio-4x3">
          <iframe src=<%= simulator_path(@project) %>></iframe>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-12 col-md-5 col-lg-5">
      <div class="container projects-details">
        <div class="row center-row projects-details-heading-container">
          <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <div class="projects-details-heading">
              <%= @project.name %>
            </div>
          </div>
        </div>
        <div class="row projects-views-count-container noSelect">
          <i class="fas fa-star projects-star-count-icon" aria-hidden="true"></i>
          <span id="star-count" class="noSelect"><%= @project.stars.count %></span>
           <%= t("projects.stars_count") %>
          &nbsp; &nbsp;
          <i class="fa fa-eye" aria-hidden="true"></i>
          <span id="star-count" class="noSelect"><%= @project.view %></span>
           <%= t("projects.views_count") %> &nbsp; &nbsp;
        </div>
        <div class="row center-row projects-user-details-container">
          <div class="projects-search-tags-container">
            <% if !@project.tags.empty? %>
              <% @project.tags.each do |tag| %>
                <%= link_to tag.name, tag_path(tag.name), class: "badge search-tag" %>
              <% end %>
            <% end %>
          </div>
          <p>
            <strong><%= t("projects.show.project_author") %> </strong>
            <%= link_to @project.author.name, @project.author, class: "anchor-text" %>
          </p>
          <% if !@project.forked_project.nil? %>
            <p>
              <strong><%= t("projects.show.project_forked_from") %> </strong>
              <%= link_to "#{@project.forked_project.author.name}/#{@project.forked_project.name}", user_project_path(@project.forked_project.author, @project.forked_project), class: "anchor-text" %>
            </p>
          <% end %>
          <p>
            <strong><%= t("projects.show.project_access_type") %> </strong>
            <%= @project.project_access_type %>
          </p>
          <% if !@project.description.nil? %>
            <p>
              <strong><%= t("projects.show.project_description") %> </strong>
            </p>
            <div class="projects-details-description"><%= sanitize @project.description %></div>
          <% end %>
          <p title="<%= @project.created_at.strftime("%B %d, %Y, %l:%M %p UTC %:z") %>">
            <strong><%= t("projects.show.project_created_at") %> </strong>
            <% if @project.created_at >= 14.days.ago %>
              <%= "#{time_ago_in_words(@project.created_at, include_seconds: true)} ago" %>
            <% else %>
             <%= @project.created_at.strftime("%b %d, %Y") %>
            <% end %>
          </p>
          <p title="<%= @project.updated_at.strftime("%B %d, %Y, %l:%M %p UTC %:z") %>">
            <strong><%= t("projects.show.project_updated_at") %> </strong>
            <% if @project.updated_at >= 14.days.ago %>
              <%= "#{time_ago_in_words(@project.updated_at, include_seconds: true)} ago" %>
            <% else %>
              <%= @project.updated_at.strftime("%b %d, %Y") %>
            <% end %>
          </p>
          <% if user_signed_in? %>
            <p>
              <hr class="projects-horizontal-rule">
              <% if policy(@project).user_access? %>
                <a href="<%= simulator_edit_path(@project) %>" class="btn primary-button projects-primary-button" target="_blank" rel="noopener noreferrer"><%= t("launch_simulator") %></a>
              <% else %>
                <a class="btn primary-button projects-self-embed-button" class="embed-trigger" href="#" data-bs-target="#embedProjectCircuit" data-bs-toggle="modal">
                <i class="fas fa-code"></i>
                <span><%= t("projects.show.project_embed") %></span>
              </a>
              <% end %>
              <% if policy(@project).author_access? %>
                <%= link_to create_fork_project_path(@project), id: "copy_paste", class: "btn primary-button projects-primary-button", method: :post do %>
                  <%= image_tag("SVGs/createCopy.svg", alt: "Create Copy") %>
                  <span><%= t("projects.show.project_copy") %></span>
                <% end %>
              <% else %>
                  <%= link_to create_fork_project_path(@project), class: "btn primary-button projects-primary-button", method: :post do %>
                  <%= image_tag("SVGs/forkProject.svg", alt: "Fork Project") %>
                  <span><%= t("fork") %></span>
                <% end %>
              <% end %>
              <% if @project.stars.exists?(user_id: current_user.id) %>
                <i id="toggleStarButton" class="fas fa-star btn primary-button projects-primary-button projects-button-star-icon" aria-hidden="true" onclick="toggleStar()"></i>
              <% else %>
                <i id="toggleStarButton" class="far fa-star btn primary-button projects-primary-button projects-button-star-icon" aria-hidden="true" onclick="toggleStar()"></i>
              <% end %>
            </p>
          <% end %>
          <% if policy(@project).author_access? %>
            <p id="collaboration_button">
              <a href="#" class="anchor-text" id="<%= @project.id %>" data-bs-toggle="modal" data-bs-target="#collaboratorModal"><%= t("projects.show.project_collaborator_add") %></a>
            </p>
          <% end %>
          <% if policy(@project).user_access? %>
            <hr class="projects-horizontal-rule">
            <p>
              <%= link_to edit_user_project_path(@author, @project), class: "btn secondary-button ml-0 py-1 px-2 d-inline-flex justify-content-center align-items-center" do %>
                <%= image_tag("SVGs/editProject.svg", alt: "Edit Project") %>
                <span><%= t("edit") %></span>
              <% end %>
              <%= link_to "#", class: "btn secondary-button ml-0 py-1 px-2 d-inline-flex justify-content-center align-items-center", data: { bs_toggle: "modal", bs_target: "#deleteprojectModal", currentauthor: @author.id, currentproject: @project.id } do %>
                <%= image_tag("SVGs/deleteProject.svg", alt: "Delete Project") %>
                <span><%= t("delete") %></span>
              <% end %>
              <a class="btn secondary-button ms-0 py-1 px-2 d-inline-flex justify-content-center align-items-center projects-self-embed-button embed-trigger" href="#" data-bs-target="#embedProjectCircuit" data-bs-toggle="modal">
                <i class="fas fa-code me-1"></i>
                <span><%= t("projects.show.project_embed") %></span>
              </a>
              </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <br>
  <% collaborators = @project.collaborators %>
    <% if collaborators.count!=0 %>
      <div class="row center-row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
          <div class="projects-collaborators-container">
            <div class="row center-row">
              <div class="col-12 col-sm-12 col-md-12 col-lg-12 projects-collaborators-heading">
                <div class="">
                  <%= t("projects.show.collaborators") %>
                </div>
              </div>
            </div>
            <% @project.collaborators.each do |user| %>
              <div class="row center-row">
                <div class="col-12 col-sm-12 col-md-4 col-lg-4">
                  <div class="projectshow-collaborators-userdata">
                    <%= link_to user.name, user, class: "anchor-text" %>
                  </div>
                </div>
                <% if policy(@project).author_access? %>
                  <div class="col-8 col-sm-8 col-md-5 col-lg-5">
                    <div class="projects-collaborators-data">
                      <%= user.email %>
                    </div>
                  </div>
                  <div class="col-4 col-sm-4 col-md-3 col-lg-3">
                    <div class="projects-collaborators-button-container">
                      <%= link_to "#", data: { bs_toggle: "modal", bs_target: "#deletecollaborationModal", currentcollaboration: Collaboration.find_by(user_id: user.id, project_id: @project.id).id }, class: "btn primary-delete-button" do %>
                        <%= image_tag("SVGs/deleteGroup.svg", alt: "Delete Collaboration") %>
                        <span><%= t("remove") %></span>
                      <% end %>
                    </div>
                  </div>
                <% end %>
                <hr class="projects-collaborators-horizontal-rule">
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <%= render partial: "add_collaborator_modal" %>
    <%= render(ProjectComponents::DeleteProjectConfirmationModelComponent.new) %>
    <%= render partial: "delete_collaboration_confirmation_modal" %>
    <%= render(ProjectEmbedComponent.new(@project)) %>

</div>

<%= commontator_thread(@project) if Flipper.enabled?(:project_comments) %>

<script>
  $(document).ready(function() {
    <% if @project&.assignment_id.present? && @project.assignment.feature_restrictions %> {
      let restricted_feature = '<%= @project.assignment.feature_restrictions %>';
      if(restricted_feature.includes('Allow Collaborators')) {
        $('#collaboration_button').attr("style", "display:none")
      }
      if(restricted_feature.includes('Copy / Paste')) {
        $('#copy_paste').attr("style", "display:none")
      }
    }
    <% end %>
    $("#deleteprojectModal").on("show.bs.modal", function(e) {
        let author = $(e.relatedTarget).data('currentauthor');
        let project = $(e.relatedTarget).data('currentproject');
        $(e.currentTarget).find('#projects-delete-button').attr("href",
        "/users/" + author.toString() + "/projects/" + project.toString());
    });
    $("#deletecollaborationModal").on("show.bs.modal", function(e) {
        let collaboration = $(e.relatedTarget).data('currentcollaboration');
        $(e.currentTarget).find('#projects-collaboration-delete-button').attr("href",
        "/collaborations/" + collaboration.toString());
    });
  })
</script>
<script>
  function toggleStar(toggle) {
    $.ajax({
      url: "<%= change_stars_path(@project) %>",
      type: 'GET',
      beforeSend: function (xhr) {
        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
      },
      success: function (response) {
        if(response == "1"){
          document.getElementById('toggleStarButton').classList.remove("fas");
          document.getElementById('toggleStarButton').classList.add("far");
          }
        else{
          document.getElementById('toggleStarButton').classList.remove("far");
          document.getElementById('toggleStarButton').classList.add("fas");
          }
          document.getElementById("star-count").innerHTML = (response == "1") ? (Number(document.getElementById("star-count").innerHTML)-1) : (Number(document.getElementById("star-count").innerHTML)+1);
        }
    });
  }
</script>
<% if user_signed_in? %>
  <script type="application/ld+json">
    {
      "@context" : "http://schema.org",
      "@type" : "Article",
      "name" : "<%= @project.name %>",
      "author" : {
        "@type" : "Person",
        "name" : "<%= @project.author.name %>"
      },
      "articleSection" : "Project",
      "articleBody" : "<%= @project.description || " " %>"
    }
  </script>
<% end %>